### PR TITLE
Paywalls: improve Chinese localization

### PR DESCRIPTION
**Pull request by aboedo**
Android equivalent to https://github.com/RevenueCat/purchases-ios/pull/3489/

I noticed that we don't have a separate file for Chinese Simplified on Android? Is this intentional?

### CODE REVIEW

**Review by tonidero — APPROVED** [review]
This looks good to me! As for why we don't have simplified chinese... I'm not sure... @NachoSoto ?

**Comment by NachoSoto** [comment]
I automated the import of languages from iOS. Let me check.

**Comment by NachoSoto** [comment]
I'm not familiar, would it be `zh`?
Screenshot 2023-12-15 at 15 44 29

**Review by NachoSoto — APPROVED** [review]

**Review by greenietea — APPROVED** [review]

**Comment by greenietea** [comment]
> I'm not familiar, would it be `zh`? Screenshot 2023-12-20 at 10 18 51

both traditional and simplified are represented as zh. 

are we meant to also have another file named: `ui/revenuecatui/src/main/res/values-zh-rHans/strings.xml` where we keep the simplified version?

**Comment by aboedo** [comment]
I can tackle adding it as a separate PR, thanks!

**Pull request merged**
