### PR TITLE
Fix log when failing to fetch offerings

### PR DESCRIPTION
**Pull request by vegaro**
Upgrading the Kotlin version triggers a compilation error. We were comparing a PurchasesError against error codes.

### CODE REVIEW

**Review by joshdholtz — APPROVED** [review]

**Comment by NachoSoto** [comment]
I think I did this (oops). I thought there was a test that covers it? I'm curious why it passed. Or maybe there's no test?

**Comment by vegaro** [comment]
There's probably no test that goes through that past. I will add one 😄 Crazy that Kotlin would compile before updating it

**Comment by vegaro** [comment]
Oh so there's actually a test `configuration error if products are not set up` that tests this. The problem is that `errorCausedByPurchases` was always false in previous versions of kotlin (in Kotlin 1.5 they became compiler errors), so it would always print the log as a `GOOGLE_ERROR`, which we are not testing. I don't know if we want to test the way we print logs though

**Comment by NachoSoto** [comment]
Oh makes sense. Never mind then.

**Pull request merged**
