### PR TITLE
Add Coroutine support to `Purchases#getCustomerInfo(callback: ReceiveCustomerInfoCallback)` API

### PR DESCRIPTION
**Pull request by pablo-guardiola**
### Checklist
- [x] If applicable, unit tests
- [ ] If applicable, create follow-up issues for `purchases-ios` and hybrids

### Motivation
*Why is this change required? What problem does it solve?*

Continuing with my exploration thought that I could kick-off https://github.com/RevenueCat/purchases-android/issues/434 work so opening this PR as a `Draft` to start the Coroutine support discussion 😊 

Some initial questions:

- What's your "policy" around adding new dependencies to the SDK?

https://github.com/RevenueCat/purchases-android/blob/04c818915a94a21fd560674cc2d90a9b5f8f6226/purchases/src/main/kotlin/com/revenuecat/purchases/Purchases.kt#L736-L737

- Do you include / test all the variants of an API in `purchase-tester` app?

https://github.com/RevenueCat/purchases-android/blob/04c818915a94a21fd560674cc2d90a9b5f8f6226/examples/purchase-tester/src/main/java/com/revenuecat/purchasetester/OverviewFragment.kt#L68-L75

For now, I commented out `getCustomerInfo(callback: ReceiveCustomerInfoCallback)` logic but happy to uncomment and test both variants, even if it's kinda duplicated. Please, let me know 🙏 

**Edit**
I see that there's `api-tester` / `PurchasesAPI`. Where do these checks run? Are these files auto-generated? Wondering how to add `getCustomerInfo` check to `PurchasesAPI.kt` / how to inject the `CoroutineScope` and `launch` the coroutine from there.

BTW, I know that #434 is about creating a separate extensions library but for now I added it directly into `Purchases`.

### Description
*Describe your changes in detail*

- Add Coroutine support to `Purchases#getCustomerInfo(callback: ReceiveCustomerInfoCallback)` API

*Please describe in detail how you tested your changes*

- Add test coverage to `PurchasesTest`
- Test manually using the `purchase-tester` app

cc @vegaro

### CODE REVIEW

**Comment by vegaro** [comment]
Thanks for opening this. We've been meaning to add coroutine support for a while and this is a good start.

We did have in mind to add it as a separate library though, so devs wouldn't get the coroutines library if they are not using them. We've seen Google libraries follow that pattern.

We need to discuss internally if we want to add this support now and how we want to do it. Thanks again for opening this as this helps us getting started with it.

**Comment by pablo-guardiola** [comment]
Thanks for following up @vegaro 🙇‍♂️ 

> We did have in mind to add it as a separate library though, so devs wouldn't get the coroutines library if they are not using them. We've seen Google libraries follow that pattern.

Sure thing! Yeah, I noted that 👇 and can accommodate.

> BTW, I know that #434 is about creating a separate extensions library but for now I added it directly into `Purchases`.

In any case, this is currently only using the limited coroutines support that comes from the Kotlin std library (wouldn't tax the size of the SDK). Although, as I mentioned, it'd be great to consider adding the coroutines library and provide full support.

Keep me posted after discussing it internally, happy to help moving this effort forward 🚀

**Comment by pablo-guardiola** [comment]
@vegaro Good thing about adding the Coroutines dependency as part of the SDK is that opens the door to implement things like a HTTP [KMM](https://kotlinlang.org/lp/mobile/) client to access RevenueCat's REST APIs. As you may know, the library code would be shared between platforms so only one codebase needs to be maintained (increasing behavior consistency and team velocity) - I noticed that HTTP / Networking logic is currently implemented in both [`purchases-android`](https://github.com/RevenueCat/purchases-android/tree/main/common/src/main/java/com/revenuecat/purchases/common) and [`purchases-ios`](https://github.com/RevenueCat/purchases-ios/tree/main/Sources/Networking).

Also, I'd expect that most of the apps integrate Coroutines already (I've recently learned that 55% of apps that use Kotlin use Coroutines in their own code and 95% of top 1000 apps use Kotlin, this was announced yesterday at I/O) so the impact on customers would be minimum. Overall, I believe pros beat cons here 👍 

BTW, worked on a quick RevenueCat's HTTP KMM client in https://github.com/pablo-guardiola/revenuecatkmmclient - please, take a look at it when you have some time, I'd love to know what you think about it :blush:

Thanks again ✌️

**Comment by vegaro** [comment]
@pablo-guardiola we've decided we are going to tackle this. If you don't mind I am going to merge this PR into a branch and I will make some changes into it and add more functions. This is a good base for us to start working on it.

Your name will still appear as contributor in the changelog.

**Review by vegaro — APPROVED** [review]

**Pull request merged**
