### PR TITLE
[AUTOMATIC] Release/7.2.1

### PR DESCRIPTION
**Pull request by RCGitBot**
**This is an automatic release.**

### RevenueCatUI
* `PaywallActivityLauncher`: new constructor for a generic `ActivityResultCaller` (#1441) via NachoSoto (@NachoSoto)
* Improve fullscreen templates in landscape orientation (#1435) via Toni Rico (@tonidero)
* `Paywalls`: improve Japanese localization (#1439) via NachoSoto (@NachoSoto)
### Other Changes
* Remove side effect from setting purchasesUpdatedListener (#1443) via Cesar de la Vega (@vegaro)
* Paywalls: Store paywall events on disk and API (1) (#1436) via Toni Rico (@tonidero)

### CODE REVIEW

**Comment by NachoSoto** [comment]
@tonidero @vegaro you're good releasing these?

**Comment by vegaro** [comment]
Yes on my end @NachoSoto

**Comment by NachoSoto** [comment]
#1436 doesn't actually store anything yet, so it should be safe to release.

**Comment by tonidero** [comment]
That's correct, it's not completely hooked up yet. So it should be safe to release

**Review by NachoSoto — APPROVED** [review]

**Pull request merged**
