### PR TITLE
[AUTOMATIC] Release/8.9.0

### PR DESCRIPTION
**Pull request by RCGitBot**
**This is an automatic release.**

### 🔄 Other Changes
* Adds X-Is-Debug-Build header (#1873) via JayShortway (@JayShortway)

### CODE REVIEW

**Comment by tonidero** [comment]
Hmm going to hold this release, but lmk if you want to ship this and I can trigger it again!

**Comment by JayShortway** [comment]
My thinking was that it is somewhat useful to ship this header at roughly the same time for Android and iOS, but it's definitely not essential.

**Comment by tonidero** [comment]
Right... Let's release it then 👍

**Comment by tonidero** [comment]
Actually, going to recreate it but making it a patch. I don't think this should be considered a new feature by devs using the SDK.

**Pull request closed without merging**
