### PR TITLE
Extract detekt job from test job

### PR DESCRIPTION
**Pull request by vegaro**
Inspired by https://github.com/RevenueCat/purchases-android/pull/942#issuecomment-1505244860

### CODE REVIEW

**Review by tonidero — APPROVED** [review]
❤️ Thanks!

Also, should we mark it as required for merging as well in github? (same as the other jobs)

**Comment by vegaro** [comment]
oh good catch

**Comment by vegaro** [comment]
oh good catch

**Review by aboedo — COMMENTED** [review]
❤️

**Pull request merged**
