### PR TITLE
Adds multidex to integration tests

### PR DESCRIPTION
**Pull request by vegaro**
I started getting single dex file errors on integration-tests when working on #885 

This PR adds multidex to integration-tests

### CODE REVIEW

**Review by tonidero — APPROVED** [review]
Hmm this makes sense since integration tests is pointing to API 16, but looking at the [documentation](https://developer.android.com/studio/build/multidex), shouldn't we also be including the multidex library + making the application inherit from `MultiDexApplication`?

That said, I don't think that's a blocker for this, but would be nice to understand it.

**Comment by vegaro** [comment]
Oh, that's a good point @tonidero . Interesting that just this change fixes it... Maybe it has something to do with ART?

**Comment by tonidero** [comment]
Hmm not sure... We could check if the multidex library is included in the final APK. But I wouldn't spend too much time on this

**Comment by vegaro** [comment]
I ran a Gradle scan build and didn't see it included. Anyways, I added the missing steps to build.gradle an AndroidManifest, so we do it properly.

**Pull request merged**
