### PR TITLE
Release/5.2.0

### PR DESCRIPTION
**Pull request by tonidero**
### API Updates

* New API to get customer info with a given `CacheFetchPolicy`
** https://github.com/RevenueCat/purchases-android/pull/546

### Other

* Validate API key
  * https://github.com/RevenueCat/purchases-android/pull/542
* Migrate from kotlin-android-extensions to kotlin-parcelize
  * https://github.com/RevenueCat/purchases-android/pull/545
* Removed private typealiases to fix generated documentation
  * https://github.com/RevenueCat/purchases-android/pull/554
* Fix for Amazon purchase dialog not showing up
  * https://github.com/RevenueCat/purchases-android/pull/552
* Added a log when `autoSyncPurchases` is disabled
  * https://github.com/RevenueCat/purchases-android/pull/555
* Attempt to reconnect to BillingClient when Billing response is error
  * https://github.com/RevenueCat/purchases-android/pull/558

[Full Changelog](https://github.com/revenuecat/purchases-android/compare/5.1.1...5.2.0)

### TODO
- [ ] Hold until https://github.com/RevenueCat/purchases-android/pull/550 is merged.

### CODE REVIEW

**Comment by aboedo** [comment]
@tonidero is this ready for review? If so, feel free to request review, even if you don't merge until the related PR is merged

**Review by vegaro — APPROVED** [review]

**Comment by aboedo** [comment]
we should try to get a build out today. Maybe we can either do a separate release branch or just repurpose (and rebase) this one, but we need to get something out for the fix for amazon for hybrids (and the ANRs fix would be great too)

**Comment by aboedo** [comment]
@vegaro any concerns on your side w/regards to the amazon fix, or should we be ready to 🚢  it?

**Comment by vegaro** [comment]
I tested it before leaving for vacation and it looked good. Let me run a last LAT test from this branch to make sure it can make purchases

**Comment by vegaro** [comment]
I have rebased this on top of `main` so we can release it without the fastlane changes, since there are some important bugfixes that are blocking hybrid's releases

**Comment by aboedo** [comment]
do it

**Pull request merged**
