### PR TITLE
Create run configuration for CustomEntitlementComputationSample

### PR DESCRIPTION
**Pull request by vegaro**
Changing the run configuration so it shows `CustomEntitlementComputationSample` instead of `app`

### CODE REVIEW

**Review by aboedo — APPROVED** [review]

**Review by tonidero — APPROVED** [review]

**Comment by aboedo** [comment]
Screenshot 2023-07-21 at 6 45 38 PM
Update: I get an error when I try this, saying module not available. And the modules listed there don't really help

**Comment by tonidero** [comment]
> Update: I get an error when I try this, saying module not available. And the modules listed there don't really help

Are you opening the `CustomEntitlementComputation` app as a separate Android project? I find it's strange this is part of the root `./run` folder. Shouldn't this be inside the `CustomEntitlementComputation` project folder @vegaro ?

**Comment by vegaro** [comment]
There's an alternative to storing this in `.run`, we can store it inside the `.idea` folder in the `CustomEntitlementComputation` project. 

Another alternative is to add this to the project in `settings.gradle`, but I would like to avoid that option since it will mean compiling the project every time we make the project. But maybe it's what we want to do?

**Comment by tonidero** [comment]
> There's an alternative to storing this in .run, we can store it inside the .idea folder in the CustomEntitlementComputation project.

The `.idea` folder isn't usually checked-in right? I guess we could, but we would have to see what exactly we check in.


> Another alternative is to add this to the project in settings.gradle, but I would like to avoid that option since it will mean compiling the project every time we make the project

Seems like that would solve the weirdness we currently have? Maybe we can try to benchmark how much it would increase compilation times?

**Comment by vegaro** [comment]
I followed a different approach by renaming the module. What do you think @tonidero and @aboedo?

**Comment by tonidero** [comment]
I think that's ok. But if we end up making it a completely separate project, maybe we don't need to do this? As long as the main SDK run configurations don't appear to make things confusing.

**Comment by vegaro** [comment]
It's a separate project at the moment, it just has the includeBuild, which we can leave commented out as it's only for local development. I think @aboedo was confused by the fact the run configuration said just `app`, although that's pretty common in Android apps

**Comment by tonidero** [comment]
Then, I think we should just close this considering it's a separate project? I think the confusion after commenting out the `includeBuild` is much reduced. Thoughts?

**Pull request closed without merging**
