### PR TITLE
[AUTOMATIC] Release/5.7.0

### PR DESCRIPTION
**Pull request by revenuecat-ops**
**This is an automatic release.**

### New Features
* Add package name to all requests headers (#618) via Toni Rico (@tonidero)
### Other Changes
* Update releasing instructions (#602) via Cesar de la Vega (@vegaro)
* Move to SNAPSHOT version on every commit to main if needed (#611) via Toni Rico (@tonidero)

### CODE REVIEW

**Comment by vegaro** [comment]
@tonidero do you think this should go as minor? It looks like since your PR #618 is tagged as `feat` it should be a minor. But I am not sure if that change deserves a minor

**Comment by aboedo** [comment]
public API remains the same, no need for it to be a minor... do we have any tags that feel appropriate for something like it? If not we should come up with it

**Comment by vegaro** [comment]
Yeah, I don't think it should have been labeled with `new_feature` but there's really not other label that would match in a better way. 

The description of `refactor`: `A code change that neither fixes a bug nor adds a feature` would match, but it's not really a refactor... Maybe we should rename the `refactor` label to be more generic?

**Comment by tonidero** [comment]
Yeah... maybe we should do `refactor` for any non-user-facing changes, even if they are adding new features that only affects internally... I will change the label in that PR now and we can retrigger this job so it creates a patch release instead.

**Comment by vegaro** [comment]
Going to close this one and rerun it

**Pull request closed without merging**
