### PR TITLE
Proration mode on subscription upgrade

### PR DESCRIPTION
**Pull request by realsoc**
This PR resolves the issue #85 

The UpgradeInfo object carries the oldSku (mandatory) and the prorationMode (optional), which replace the old parameter oldSku in makePurchase()

The unit tests have been updated.

### CODE REVIEW

**Comment by Narayane** [comment]
@jeiting @vegaro :)

**Comment by vegaro** [comment]
Hey! This looks good to me. I guess my only comment is that it breaks compilation so it would be wise to either deprecate the old method or to add the proration parameter as an optional with a default value (without the UpgradeInfo class). It also looks like there are some formatting inconsistencies. 

We are preparing a new 3.0 update in the SDK, I can include these changes in that version if you prefer, that way we can break compilation. I also need to make sure our backend is cool with this proration modes.

**Comment by realsoc** [comment]
@vegaro I made some changes aiming at not breaking compilation.
 I thought about just add a new optional parameter instead of a new class, but it would add the possible inconsistency (oldSku == null && prorationMode != null) in the private method.
But I can restrain the usage of the upgradeInfo class and not expose it to the user. 
As you wish.

**Comment by vegaro** [comment]
Thanks for the PR, will merge this and release it with the new 3.0.0 version which is coming out soon. I removed the deprecated methods since we are already changing them :)

**Pull request merged**
